name: Release

on:
  push:
    tags: ["v*.*.**"]

jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v3
        with: 
          go-version: 1.17 # only for build windows/arm64
      - uses: goreleaser/goreleaser-action@v4.2.0
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with: 
          args: "release --rm-dist"
          version: latest