name: "Tests"

on:
  push:
    branches:
      - master
      - wip
    paths:
      - "**.go"
      - "go.mod"
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: make ci

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m
